v = "WGSN"
panel_label = v
panel_name = v.upper()
array_name = f"array_{v.lower()}"

array = [
    # ["Class Name","Tool Tip","Button Label","ID Name","Hex Color"],
    ["WGSN_NeoMint", "Neo Mint (Coloro 065-80-23)", "Neo Mint", "wgsn_neo_mint", "a6d3aa"],
    ["WGSN_Cantaloupe", "Cantaloupe (Coloro 020-72-30)", "Cantaloupe", "wgsn_cantaloupe", "f59f7e"],
    ["WGSN_Cassis", "Cassis (Coloro 145-58-21)", "Cassis", "wgsn_cassis", "ac6f81"],
    ["WGSN_MellowYellow", "Mellow Yellow (Coloro 034-70-33)", "Mellow Yellow", "wgsn_mellow_yellow", "e2ab36"],
    ["WGSN_PuristBlue", "Purist Blue (Coloro 093-76-17)", "Purist Blue", "wgsn_purist_blue", "85c6cc"],
    ["WGSN_AIAqua", "A.I. Aqua (Coloro 098-59-30)", "A.I. Aqua", "wgsn_ai_aqua", "00a5b9"],
    ["WGSN_GoodGray", "Good Gray (Coloro 122-66-02)", "Good Gray", "wgsn_good_gray", "a0abb1"],
    ["WGSN_LemonSherbet", "Lemon Sherbet (Coloro 046-85-28)", "Lemon Sherbet", "wgsn_lemon_sherbet", "f2de6b"],
    ["WGSN_OxyFire", "Oxy Fire (Coloro 015-50-36)", "Oxy Fire", "wgsn_oxy_fire", "dc493f"],
    ["WGSN_QuietWave", "Quiet Wave (Coloro 072-69-24)", "Quiet Wave", "wgsn_quiet_wave", "75c095"],
    ["WGSN_GoldenHarvest", "Golden Harvest (Coloro 034-70-21)", "Golden Harvest", "wgsn_golden_harvest", "daad6a"],
    ["WGSN_Bloodstone", "Bloodstone (Coloro 011-27-26)", "Bloodstone", "wgsn_bloodstone", "7f252e"],
    ["WGSN_DarkSprings", "Dark Springs (Coloro 087-20-02)", "Dark Springs", "wgsn_dark_springs", "2a3332"],
    ["WGSN_ElectricMagenta", "Electric Magenta (Coloro 001-35-31)", "Electric Magenta", "wgsn_electric_magenta", "ae1943"],
    ["WGSN_OrchidFlower", "Orchid Flower (Coloro 150-38-31)", "Orchid Flower", "wgsn_orchid_flower", "a1346d"],
    ["WGSN_Butter", "Butter (Coloro 040-86-20)", "Butter", "wgsn_butter", "ebdf97"],
    ["WGSN_OliveOil", "Olive Oil (Coloro 044-52-13)", "Olive Oil", "wgsn_olive_oil", "8d8054"],
    ["WGSN_MangoSorbet", "Mango Sorbet (Coloro 030-67-34)", "Mango Sorbet", "wgsn_mango_sorbet", "ec972d"],
    ["WGSN_AtlanticBlue", "Atlantic Blue (Coloro 115-35-20)", "Atlantic Blue", "wgsn_atlantic_blue", "375b7f"],
    ["WGSN_Honeycomb", "Honeycomb (Coloro 034-76-27)", "Honeycomb", "wgsn_honeycomb", "f8c761"],
    ["WGSN_Jade", "Jade (Coloro 062-57-10)", "Jade", "wgsn_jade", "839177"],
    ["WGSN_DarkOak", "Dark Oak (Coloro 017-23-07)", "Dark Oak", "wgsn_dark_oak", "413735"],
    ["WGSN_LazuliBlue", "Lazuli Blue (Coloro 122-25-24)", "Lazuli Blue", "wgsn_lazuli_blue", "32477c"],
    ["WGSN_DigitalLavender", "Digital Lavender (Coloro 134-67-16)", "Digital Lavender", "wgsn_digital_lavender", "b1a5cd"],
    ["WGSN_LusciousRed", "Luscious Red (Coloro 010-46-36)", "Luscious Red", "wgsn_luscious_red", "e33443"],
    ["WGSN_Sundial", "Sundial (Coloro 028-59-26)", "Sundial", "wgsn_sundial", "cc842f"],
    ["WGSN_TranquilBlue", "Tranquil Blue (Coloro 72-29-717)", "Tranquil Blue", "wgsn_tranquil_blue", "528ccc"],
    ["WGSN_Verdigris", "Verdigris (Coloro 092-38-21)", "Verdigris", "wgsn_verdigris", "016d6d"],
    ["WGSN_AstroDust", "Astro Dust (Coloro 010-42-20)", "Astro Dust", "wgsn_astro_dust", "a34e51"],
    ["WGSN_GalacticCobalt", "Galactic Cobalt (Coloro 120-28-32)", "Galactic Cobalt", "wgsn_galactic_cobalt", "274585"],
    ["WGSN_SageLeaf", "Sage Leaf (Coloro 072-45-06)", "Sage Leaf", "wgsn_sage_leaf", "66786c"],
    ["WGSN_ApricotCrush", "Apricot Crush (Coloro 024-65-27)", "Apricot Crush", "wgsn_apricot_crush", "e39360"],
    ["WGSN_ApricotCrush", "Apricot Crush (Coloro 024-65-27)", "Apricot Crush", "wgsn_apricot_crush", "f39154"],
    ["WGSN_CyberLime", "Cyber Lime (Coloro 051-76-36)", "Cyber Lime", "wgsn_cyber_lime", "d0c81d"],
    ["WGSN_ElementalBlue", "Elemental Blue (Coloro 117-47-13)", "Elemental Blue", "wgsn_elemental_blue", "5a7a91"],
    ["WGSN_FondantPink", "Fondant Pink (Coloro 147-70-20)", "Fondant Pink", "wgsn_fondant_pink", "d8a2c2"],
    ["WGSN_Nutshell", "Nutshell (Coloro 024-37-20)", "Nutshell", "wgsn_nutshell", "865132"],
    ["WGSN_RadiantRed", "Radiant Red (Coloro 011-50-32)", "Radiant Red", "wgsn_radiant_red", "db4c50"],
    ["WGSN_CoolMatcha", "Cool Matcha (Coloro 055-85-20)", "Cool Matcha", "wgsn_cool_matcha", "dff4b3"],
    ["WGSN_SustainedGrey", "Sustained Grey (Coloro 035-73-04)", "Sustained Grey", "wgsn_sustained_grey", "babbb5"],
    ["WGSN_MidnightPlum", "Midnight Plum (Coloro 151-22-09)", "Midnight Plum", "wgsn_midnight_plum", "4a3343"],
    ["WGSN_IntenseRust", "Intense Rust (Coloro 015-33-25)", "Intense Rust", "wgsn_intense_rust", "78291a"],
    ["WGSN_FutureDusk", "Future Dusk (Coloro 129-35-18)", "Future Dusk", "wgsn_future_dusk", "4C5578"],
    ["WGSN_AquaticAwe", "Aquatic Awe (Coloro 086-70-25)", "Aquatic Awe", "wgsn_aquatic_awe", "5DC7B7"],
    ["WGSN_RayFlower", "Ray Flower (Coloro 037-82-32)", "Ray Flower", "wgsn_ray_flower", "FFCA5C"],
    ["WGSN_SunsetCoral", "Sunset Coral (Coloro 009-58-31)", "Sunset Coral", "wgsn_sunset_coral", "F0686C"],
    ["WGSN_TranscendentPink", "Transcendent Pink (Coloro 021-80-08)", "Transcendent Pink", "wgsn_transcendent_pink", "E3B8C9"],
    ["WGSN_CelestialYellow", "Celestial Yellow (Coloro 048-90-17)", "Celestial Yellow", "wgsn_celestial_yellow", "EDEAB1"],
    ["WGSN_CherryLacquer", "Cherry Lacquer (Coloro 159-23-15)", "Cherry Lacquer", "wgsn_cherry_lacquer", "512C3A"],
    ["WGSN_RetroBlue", "Retro Blue (Coloro 100-64-14)", "Retro Blue", "wgsn_retro_blue", "71ADBA"],
    ["WGSN_NeonFlare", "Neon Flare (Coloro 014-68-51)", "Neon Flare", "wgsn_neon_flare", "FF654F"],
    ["WGSN_TransformativeTeal", "Transformative Teal (Coloro 092-357-14)", "Transformative Teal", "wgsn_transformative_teal", "366f70"],
    ["WGSN_BlueAura", "Blue Aura (Coloro 117-77-06)", "Blue Aura", "wgsn_blue_aura", "bed0dc"],
    ["WGSN_ElectricFuchsia", "Electric Fuchsia (Coloro 144-57-41)", "Electric Fuchsia", "wgsn_electric_fuchsia", "ee67db"],
    ["WGSN_JellyMint", "Jelly Mint (Coloro 078-80-22)", "Jelly Mint", "wgsn_jelly_mint", "9ddbc9"],
    ["WGSN_AmberHaze", "Amber Haze (Coloro 043-65-31)", "Amber Haze", "wgsn_amber_haze", "dbb62f"],
    ["WGSN_WaxPaper", "Wax Paper (Coloro 035-88-12)", "Wax Paper", "wgsn_wax_paper", "f7e4c5"],
    ["WGSN_FreshPurple", "Fresh Purple (Coloro 136-32-33)", "Fresh Purple", "wgsn_fresh_purple", "724e9a"],
    ["WGSN_CocoaPowder", "Cocoa Powder (Coloro 008-35-06)", "Cocoa Powder", "wgsn_cocoa_powder", "735b5f"],
    ["WGSN_GreenGlow", "Green Glow (Coloro 057-82-32)", "Green Glow", "wgsn_green_glow", "cee270"],
    ["WGSN_LuminousBlue", "Luminous Blue (Coloro 125-28-38)", "Luminous Blue", "wgsn_luminous_blue", "193f8f"],
    ["WGSN_EnergyOrange", "Energy Orange (Coloro 018-57-34)", "Energy Orange", "wgsn_energy_orange", "ee6643"],
    ["WGSN_MeadowlandGreen", "Meadowland Green (Coloro 050-61-19)", "Meadowland Green", "wgsn_meadowland_green", "a39e58"],
    ["WGSN_Clay", "Clay (Coloro 014-60-13)", "Clay", "wgsn_clay", "c38b84"],
    ["WGSN_PopPink", "Pop Pink (Coloro 151-73-22)", "Pop Pink", "wgsn_pop_pink", "eaa6c5"]
]
